name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Type check
        run: npm run typecheck

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run tests
        run: npm test -- --test-concurrency=1

  isolated-vm-build-and-test:
    name: isolated-vm ${{ matrix.os }} / Node ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [24]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Add msbuild to PATH
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v2

      - name: Install node-gyp
        if: matrix.os == 'windows-latest'
        run: npm install --global node-gyp@latest

      - name: Build isolated-vm
        run: npm install --build-from-source
        working-directory: vendor/isolated-vm

      - name: Test isolated-vm
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 6
          command: |
            cd vendor/isolated-vm
            npm test

  isolated-vm-build-and-test-alpine:
    name: isolated-vm alpine / Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [24]
      fail-fast: false
    container: node:${{ matrix.node }}-alpine

    steps:
      - name: Install checkout dependencies
        run: apk add --no-cache git bash

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build dependencies
        run: apk add g++ make python3

      - name: Build isolated-vm
        run: npm install --build-from-source
        working-directory: vendor/isolated-vm

      - name: Test isolated-vm
        run: npm test
        working-directory: vendor/isolated-vm
        timeout-minutes: 4
