name: direct-publish

on:
  workflow_dispatch:

jobs:
  publish:
    name: Direct Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Ensure main branch
        run: |
          if [ "${GITHUB_REF}" != "refs/heads/main" ]; then
            echo "This workflow can only be run from main."
            exit 1
          fi
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - name: Update npm
        run: npm install -g npm@latest
      - run: npm ci
      - run: npm run build:npm
      - run: npx changeset publish --access=public --registry=https://registry.npmjs.org/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
